// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR8j5-szQfeBFyrXzYZ0BmB8kXNstJbyg',
    appId: '1:844295744349:web:1b8bc0a6db1a11c3f116b4',
    messagingSenderId: '844295744349',
    projectId: 'kora-byte',
    authDomain: 'kora-byte.firebaseapp.com',
    storageBucket: 'kora-byte.appspot.com',
    measurementId: 'G-WRHSGRSKRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsKyA6SSR1flBprCiSv_82unriIb-HkYI',
    appId: '1:844295744349:android:95642557bfaf9306f116b4',
    messagingSenderId: '844295744349',
    projectId: 'kora-byte',
    storageBucket: 'kora-byte.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArwDgFmuma8XW7REVRMB7LXXOFpQBnmJs',
    appId: '1:844295744349:ios:e1fc3e8ed8d77db3f116b4',
    messagingSenderId: '844295744349',
    projectId: 'kora-byte',
    storageBucket: 'kora-byte.appspot.com',
    iosBundleId: 'com.example.koraNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArwDgFmuma8XW7REVRMB7LXXOFpQBnmJs',
    appId: '1:844295744349:ios:e1fc3e8ed8d77db3f116b4',
    messagingSenderId: '844295744349',
    projectId: 'kora-byte',
    storageBucket: 'kora-byte.appspot.com',
    iosBundleId: 'com.example.koraNews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR8j5-szQfeBFyrXzYZ0BmB8kXNstJbyg',
    appId: '1:844295744349:web:85695f6a3af0d743f116b4',
    messagingSenderId: '844295744349',
    projectId: 'kora-byte',
    authDomain: 'kora-byte.firebaseapp.com',
    storageBucket: 'kora-byte.appspot.com',
    measurementId: 'G-47JP94RN3H',
  );
}
